// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RealApiData.Models;

public partial class Product
{
    [Key]
    public int id { get; set; }

    [Required]
    [Unicode(false)]
    public string ProductName { get; set; }

    public int? ProductPrice { get; set; }

    public int? Quantity { get; set; }

    [StringLength(255)]
    
    public string ImageUrl { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Description { get; set; }

    
}