// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RealApiData.Models;

public partial class User
{
    [Key]
    public int id { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Email { get; set; }

    public bool IsAdmin { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Password { get; set; }
}